version: "3.8"

services:
  client:
    build: ./client
    container_name: phonebook-client
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  server:
    build: ./server
    container_name: phonebook-server
    ports:
      - "4000:4000"
    env_file:
      - server/.env
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail http://localhost:4000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
  db:
    image: postgres:alpine
    env_file:
      - server/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d book || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
