version: "3.8"

services:
  client:
    build: ./client
    container_name: phonebook-client
    ports:
      - "8080:8080"
  server:
    build: ./server
    container_name: phonebook-server
    ports:
      - "4000:4000"
    env_file:
      - server/.env
  db:
    image: postgres:alpine
    env_file:
      - server/.env
    # environment:
    #   - POSTGRES_USER=admin
    #   - POSTGRES_PASSWORD=admin
    #   - POSTGRES_DB=book
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
