version: "3.8"

services:
  server:
    image: server
    ports:
      - "4000:4000"
    env_file:
      - .env
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${dbName}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
